[package]
name = "router_egui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "eve-router-egui"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["glow", "default_fonts", "accesskit", "links", "wayland", "x11"] }
egui = "0.36.2"
egui_extras = "0.36.2"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png"] }
mimalloc.workspace = true
petgraph.workspace = true
rayon.workspace = true
router_core.workspace = true

[dev-dependencies]
router_core = { workspace = true, features = ["test-support"] }
